# Localization generation configuration
arb-dir: lib/l10n
# Ukrainian is the source/template language
template-arb-file: app_uk.arb
output-localization-file: app_localizations.dart
untranslated-messages-file: untranslated_messages.txt
output-class: AppLocalizations
preferred-supported-locales: ['uk', 'en']